---
before_install:
    - 'yarn upgrade'
cache: yarn
branches:
    only:
        - master
install:
    - 'yarn'
language: node_js
node_js:
    - node
script:
    - 'yarn build'
    - 'yarn coverage'
sudo: false
